[project]
ref = "your-project-ref"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

# Network permissions for all audio platforms
[functions]
net = ["api.fish.audio", "api.elevenlabs.io", "api.minimax.chat"]

# Fish Audio functions
[functions.fetch-fish-audio-voice]
net = ["api.fish.audio"]

[functions.list-fish-audio-voices]
net = ["api.fish.audio"]

# ElevenLabs functions
[functions.fetch-elevenlabs-voice]
net = ["api.elevenlabs.io"]

[functions.list-elevenlabs-voices]
net = ["api.elevenlabs.io"]

# Minimax functions
[functions.fetch-minimax-voice]
net = ["api.minimax.chat"]

[functions.list-minimax-voices]
net = ["api.minimax.chat"]

[auth]
enabled = true