name: autodark-app
services:
  - type: app
    data:
      name: autodark
      source:
        type: github
        repo: FresHHerB/autodark
        branch: main
      build:
        type: dockerfile
        dockerfile: Dockerfile
        buildArgs:
          - name: VITE_SUPABASE_URL
            value: https://vstsnxvwvsaodulrvfjz.supabase.co
          - name: VITE_SUPABASE_ANON_KEY
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdHNueHZ3dnNhb2R1bHJ2Zmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjM3OTMsImV4cCI6MjA3MzYzOTc5M30.QNtDCN4CwQ8ZLB2vENZh_K0Kwdd6nwFog0L8xlgAugs
          - name: VITE_API_BASE_URL
            value: https://n8n-n8n.gpqg9h.easypanel.host
          - name: VITE_WEBHOOK_CLONE_CHANNEL
            value: /webhook/treinarCanal